spring:
  application:
    name: Tudu
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info,mappings,beans,metrics,env,trace,heapdump,threaddump"
